// Generated by https://quicktype.io

export interface NanoContext {
  apps: App[];
  nanoConfig: NanoConfig;
}

export interface App {
  ID: number;
  CreatedAt: string;
  UpdatedAt: string;
  DeletedAt: string;
  appName: string;
  appStatus: string;
  envVal: string;
  envMountPath: string;
  buildVal: string;
  buildValMountPath: string;
  repoUrl: string;
}

export interface NanoConfig {
  globalEnvironment: string;
  token: string;
}
